osx_image: xcode10.1
language: objective-c
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem update --system
  - sudo gem install bundler
  - bundle install
script: bundle exec fastlane ValidorFormTests
