osx_image: xcode10.1
language: objective-c
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
#install: bundle exec pod install --repo-udate --silent
script: bundle exec fastlane ValidorFormTests
