# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :ValidorFormTests do
    run_tests(scheme: "ValidorFormTests")
    # add actions here: https://docs.fastlane.tools/actions

    if git_branch() == 'develop'
      pod_push(path: 'ValidorForm.podspec', allow_warnings: true)
    end

    if git_branch() == 'master'
      slack(message: 'Hello push version: ' + get_version_number())
      pod_push(path: 'ValidorForm.podspec', allow_warnings: true)
    end
  end

  lane :ValidorFormTests do
  run_tests(scheme: "ValidorFormTests",
            slack_url: "https://hooks.slack.com/services/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",
            slack_channel: "#cocoswift")
  end
end
