# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all iOS tests and Build/Deploy on Travis CI"
  lane :ValidorFormTests do
    run_tests(
      scheme: "ValidorFormTests",
      slack_url: "https://hooks.slack.com/services/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",
      slack_channel: "#cocoswift")
    # add actions here: https://docs.fastlane.tools/actions

    if git_branch() == 'develop'
      #pod_push(path: 'ValidorForm.podspec', repo: 'ValidorForm', allow_warnings: true)
      pod_push(path: 'ValidorForm.podspec', repo: 'ValidorForm', allow_warnings: true)
      #eq("pod repo push ValidorForm 'ValidorForm.podspec' --allow-warnings")
    end

    if git_branch() == 'master'
      slack(message: 'Hello push version: ' + get_version_number(), success: true, default_payloads: [:git_branch, :last_git_commit_message])
      pod_push(path: 'ValidorForm.podspec', repo: 'ValidorForm', allow_warnings: true)
    end
  end
end
